# -*- coding: utf-8 -*-
"""
Created on Fri May 31 15:03:47 2019

@author: nrandle
"""
norepeats = [
 'Machine Learning (supervised)',
 'Machine Learning (unsupervised)',
 'Machine Learning (reinforced)',
 'Data Mining Topics',
 'Test Data Mining',
 'Predictive Analytics methods',
 'Prescriptive Analytics methods',
 'Graph Data Analytics',
 'Qualitative analytics',
 'Natural Language Processing methods',
 'Data prep',
 'Performance and accuracy metrics',
 'Systems Engineering and Software Engineering principles',
 'Cloud Computing',
 'Big Data technologies',
 'Applications software requirements',
 'Systems and data security, data access',
 'Compliance based security models',
 'Relational and non-relational databases',
 'Big Data infrastructures, high-performance networks',
 'Modeling and simulation, theory and systems',
 'Information systemss',
 'Data management and enterprise data infrastructure',
 'Data storage systems',
 'Data governance, Data Management Plan',
 'Data Architecture',
 'Data lifecycle and organisational workflow',
 'Data curation',
 'Data protection',
 'Metadata, PID, data registries, data factories',
 'Open Data, Open Science, Open Access, ORCID',
 'Research methods, research cycle',
 'Experiment design',
 'Data lifecycle and data collection',
 'Use-cases analysis: research infrastructure and projects',
 'Research Data Management Plan and data stewardship',
 'Project management',
 'Business Analytics and Business Intelligence',
 'Business Processes Management',
 'Agile Data Driven methodologies',
 'Econometrics for data analysis',
 'Data driven Customer Relations Management',
 'Use-cases analysis: business and industry',
 'Data Warehouses technologies, data integration and analytics',
 'Data driven marketing technologies',
 'Use Machine Learning tools',
 'Use Data Mining techniques',
 'Use Text Data Mining techniques',
 'Apply Graph Data Analytics for organisational network analysis',
 'Apply Analytics and statistics methods for data prep',
 'use performance and accuracy metrics for data analytics',
 'visualiation and storytelling methods',
 'Operations Research',
 'Optimisation',
 'Simulation',
 'Use Cloud Computing technologies',
 'organisational Information systems',
 'Design efficient algorithms for large amounts of data',
 'Recommender or Ranking system',
 'enterprise data management',
 'implementation of the hybrid data management infrastructure',
 'Develop and implement data architecture',
 'Consistently implement data curation and data quality controls',
 'Implement data protection',
 'Adhere to the principles of the Open Data',
 'developing data driven applications',
 'data collection process',
 'Apply structured approach to use cases analysis',
 'Develop and implement Research Data Management Plan',
 'Consistently apply project management workflow',
 'Apply structured approach to use cases analysis in business and industry',
 'Mechanism Design and/or Latent Dirichlet Allocation']

x = ['Machine Learning (supervised)',
'Machine Learning (supervised)',
'Machine Learning (supervised)',
'Machine Learning (supervised)',
'Machine Learning (supervised)',
'Machine Learning (supervised)',
'Machine Learning (supervised)',
'Machine Learning (unsupervised)',
'Machine Learning (unsupervised)',
'Machine Learning (unsupervised)',
'Machine Learning (unsupervised)',
'Machine Learning (unsupervised)',
'Machine Learning (unsupervised)',
'Machine Learning (unsupervised)',
'Machine Learning (reinforced)',
'Machine Learning (reinforced)',
'Machine Learning (reinforced)',
'Machine Learning (reinforced)',
'Machine Learning (reinforced)',
'Machine Learning (reinforced)',
'Machine Learning (reinforced)',
'Data Mining Topics',
'Data Mining Topics',
'Data Mining Topics',
'Data Mining Topics',
'Data Mining Topics',
'Data Mining Topics',
'Data Mining Topics',
'Test Data Mining',
'Test Data Mining',
'Test Data Mining',
'Test Data Mining',
'Text Data Mining',
'Test Data Mining',
'Test Data Mining',
'Predictive Analytics methods',
'Predictive Analytics methods',
'Predictive Analytics methods',
'Predictive Analytics methods',
'Predictive Analytics methodS',
'Predictive Analytics methods',
'Predictive Analytics methods',
'Prescriptive Analytics methods',
'Prescriptive Analytics methods',
'Prescriptive Analytics methods',
'Prescriptive Analytics methods',
'Prescriptive Analytics methods',
'Prescriptive Analytics methods',
'Prescriptive Analytics methods',
'Graph Data Analytics',
'Graph Data Analytics',
'Graph Data Analytics',
'Graph Data Analytics',
'Graph Data Analytics',
'Graph Data Analytics',
'Graph Data Analytics',
'Qualitative analytics',
'Qualitative analytics',
'Qualitative analytics',
'Qualitative analytics',
'Qualitative analytics',
'Qualitative analytics',
'Qualitative analytics',
'Natural Language Processing methods',
'Natural Language Processing methods',
'Natural Language Processing methods',
'Natural Language Processing methods',
'Natural Language Processing methods',
'Natural Language Processing methods',
'Natural Language Processing methods',
'Data prep ',
'Data prep ',
'Data prep ',
'Data prep ',
'Data prep ',
'Data prep ',
'Data prep ',
'Performance and accuracy metrics',
'Performance and accuracy metrics',
'Performance and accuracy metrics',
'Performance and accuracy metrics',
'Performance and accuracy metrics',
'Performance and accuracy metrics',
'Performance and accuracy metrics',
'Systems Engineering and Software Engineering principles',
'Systems Engineering and Software Engineering principles',
'Systems Engineering and Software Engineering principles',
'Systems Engineering and Software Engineering principles',
'Systems Engineering and Software Engineering principles',
'Systems Engineering and Software Engineering principles',
'Systems Engineering and Software Engineering principles',
'Cloud Computing',
'Cloud Computing',
'Cloud Computing',
'Cloud Computing',
'Cloud Computing',
'Cloud Computing',
'Cloud Computing',
'Big Data technologies',
'Big Data technologies',
'Big Data technologies',
'Big Data technologies',
'Big Data technologies',
'Big Data technologies',
'Big Data technologies',
'Applications software requirements',
'Applications software requirements',
'Applications software requirements',
'Applications software requirements',
'Applications software requirements',
'Applications software requirements',
'Applications software requirements',
'Systems and data security, data access',
'Systems and data security, data access',
'Systems and data security, data access',
'Systems and data security, data access',
'Systems and data security, data access',
'Systems and data security, data access',
'Systems and data security, data access',
'Compliance based security models',
'Compliance based security models',
'Compliance based security models',
'Compliance based security models',
'Compliance based security models',
'Compliance based security models',
'Compliance based security models',
'Relational and non-relational databases',
'Relational and non-relational databases',
'Relational and non-relational databases',
'Relational and non-relational databases',
'Relational and non-relational databases',
'Relational and non-relational databases',
'Relational and non-relational databases',
'Big Data infrastructures, high-performance networks',
'Big Data infrastructures, high-performance networks',
'Big Data infrastructures, high-performance networks',
'Big Data infrastructures, high-performance networks',
'Big Data infrastructures, high-performance networks',
'Big Data infrastructures, high-performance networks',
'Big Data infrastructures, high-performance networks',
'Modeling and simulation, theory and systems',
'Modeling and simulation, theory and systems',
'Modeling and simulation, theory and systems',
'Modeling and simulation, theory and systems',
'Modeling and simulation, theory and systems',
'Modeling and simulation, theory and systems',
'Modeling and simulation, theory and systems',
'Information systemss',
'Information systemss',
'Information systemss',
'Information systemss',
'Information systemss',
'Information systemss',
'Information systemss',
'Data management and enterprise data infrastructure',
'Data management and enterprise data infrastructure',
'Data management and enterprise data infrastructure',
'Data management and enterprise data infrastructure',
'Data management and enterprise data infrastructure',
'Data management and enterprise data infrastructure',
'Data management and enterprise data infrastructure',
'Data storage systems',
'Data storage systems',
'Data storage systems',
'Data storage systems',
'Data storage systems',
'Data storage systems',
'Data storage systems',
'Data governance, Data Management Plan',
'Data governance, Data Management Plan',
'Data governance, Data Management Plan',
'Data governance, Data Management Plan',
'Data governance, Data Management Plan',
'Data governance, Data Management Plan',
'Data governance, Data Management Plan',
'Data Architecture',
'Data Architecture',
'Data Architecture',
'Data Architecture',
'Data Architecture',
'Data Architecture',
'Data Architecture',
'Data lifecycle and organisational workflow',
'Data lifecycle and organisational workflow',
'Data lifecycle and organisational workflow',
'Data lifecycle and organisational workflow',
'Data lifecycle and organisational workflow',
'Data lifecycle and organisational workflow',
'Data lifecycle and organisational workflow',
'Data curation',
'Data curation',
'Data curation',
'Data curation',
'Data curation',
'Data curation',
'Data curation',
'Data protection',
'Data protection',
'Data protection',
'Data protection',
'Data protection',
'Data protection',
'Data protection',
'Metadata, PID, data registries, data factories',
'Metadata, PID, data registries, data factories',
'Metadata, PID, data registries, data factories',
'Metadata, PID, data registries, data factories',
'Metadata, PID, data registries, data factories',
'Metadata, PID, data registries, data factories',
'Metadata, PID, data registries, data factories',
'Open Data, Open Science, Open Access, ORCID',
'Open Data, Open Science, Open Access, ORCID',
'Open Data, Open Science, Open Access, ORCID',
'Open Data, Open Science, Open Access, ORCID',
'Open Data, Open Science, Open Access, ORCID',
'Open Data, Open Science, Open Access, ORCID',
'Open Data, Open Science, Open Access, ORCID',
'Research methods, research cycle',
'Research methods, research cycle',
'Research methods, research cycle',
'Research methods, research cycle',
'Research methods, research cycle',
'Research methods, research cycle',
'Research methods, research cycle',
'Experiment design',
'Experiment design',
'Experiment design',
'Experiment design',
'Experiment design',
'Experiment design',
'Experiment design',
'Data lifecycle and data collection',
'Data lifecycle and data collection',
'Data lifecycle and data collection',
'Data lifecycle and data collection',
'Data lifecycle and data collection',
'Data lifecycle and data collection',
'Data lifecycle and data collection',
'Use-cases analysis: research infrastructure and projects',
'Use-cases analysis: research infrastructure and projects',
'Use-cases analysis: research infrastructure and projects',
'Use-cases analysis: research infrastructure and projects',
'Use-cases analysis: research infrastructure and projects',
'Use-cases analysis: research infrastructure and projects',
'Use-cases analysis: research infrastructure and projects',
'Research Data Management Plan and data stewardship',
'Research Data Management Plan and data stewardship',
'Research Data Management Plan and data stewardship',
'Research Data Management Plan and data stewardship',
'Research Data Management Plan and data stewardship',
'Research Data Management Plan and data stewardship',
'Research Data Management Plan and data stewardship',
'Project management',
'Project management',
'Project management',
'Project management',
'Project management',
'Project management',
'Project management',
'Business Analytics and Business Intelligence',
'Business Analytics and Business Intelligence',
'Business Analytics and Business Intelligence',
'Business Analytics and Business Intelligence',
'Business Analytics and Business Intelligence',
'Business Analytics and Business Intelligence',
'Business Analytics and Business Intelligence',
'Business Processes Management',
'Business Processes Management',
'Business Processes Management',
'Business Processes Management',
'Business Processes Management',
'Business Processes Management',
'Business Processes Management',
'Agile Data Driven methodologies',
'Agile Data Driven methodologies',
'Agile Data Driven methodologies',
'Agile Data Driven methodologies',
'Agile Data Driven methodologies',
'Agile Data Driven methodologies',
'Agile Data Driven methodologies',
'Econometrics for data analysis',
'Econometrics for data analysis',
'Econometrics for data analysis',
'Econometrics for data analysis',
'Econometrics for data analysis',
'Econometrics for data analysis',
'Econometrics for data analysis',
'Data driven Customer Relations Management',
'Data driven Customer Relations Management',
'Data driven Customer Relations Management',
'Data driven Customer Relations Management',
'Data driven Customer Relations Management',
'Data driven Customer Relations Management',
'Data driven Customer Relations Management',
'Use-cases analysis: business and industry',
'Use-cases analysis: business and industry',
'Use-cases analysis: business and industry',
'Use-cases analysis: business and industry',
'Use-cases analysis: business and industry',
'Use-cases analysis: business and industry',
'Use-cases analysis: business and industry',
'Data Warehouses technologies, data integration and analytics',
'Data Warehouses technologies, data integration and analytics',
'Data Warehouses technologies, data integration and analytics',
'Data Warehouses technologies, data integration and analytics',
'Data Warehouses technologies, data integration and analytics',
'Data Warehouses technologies, data integration and analytics',
'Data Warehouses technologies, data integration and analytics',
'Data driven marketing technologies',
'Data driven marketing technologies',
'Data driven marketing technologies',
'Data driven marketing technologies',
'Data driven marketing technologies',
'Data driven marketing technologies',
'Data driven marketing technologies',
'Use Machine Learning tools',
'Use Machine Learning tools',
'Use Machine Learning tools',
'Use Machine Learning tools',
'Use Machine Learning tools',
'Use Machine Learning tools',
'Use Machine Learning tools',
'Use Data Mining techniques',
'Use Data Mining techniques',
'Use Data Mining techniques',
'Use Data Mining techniques',
'Use Data Mining techniques',
'Use Data Mining techniques',
'Use Data Mining techniques',
'Use Text Data Mining techniques',
'Use Text Data Mining techniques',
'Use Text Data Mining techniques',
'Use Text Data Mining techniques',
'Use Text Data Mining techniques',
'Use Text Data Mining techniques',
'Use Text Data Mining techniques',
'Apply Graph Data Analytics for organisational network analysis',
'Apply Graph Data Analytics for organisational network analysis',
'Apply Graph Data Analytics for organisational network analysis',
'Apply Graph Data Analytics for organisational network analysis',
'Apply Graph Data Analytics for organisational network analysis',
'Apply Graph Data Analytics for organisational network analysis',
'Apply Graph Data Analytics for organisational network analysis',
'Apply Analytics and statistics methods for data prep ',
'Apply Analytics and statistics methods for data prep ',
'Apply Analytics and statistics methods for data prep ',
'Apply Analytics and statistics methods for data prep ',
'Apply Analytics and statistics methods for data prep ',
'Apply Analytics and statistics methods for data prep ',
'Apply Analytics and statistics methods for data prep ',
'use performance and accuracy metrics for data analytics',
'use performance and accuracy metrics for data analytics',
'use performance and accuracy metrics for data analytics',
'use performance and accuracy metrics for data analytics',
'use performance and accuracy metrics for data analytics',
'use performance and accuracy metrics for data analytics',
'use performance and accuracy metrics for data analytics',
'visualiation and storytelling methods',
'visualiation and storytelling methods',
'visualiation and storytelling methods',
'visualiation and storytelling methods',
'visualiation and storytelling methods',
'visualiation and storytelling methods',
'visualiation and storytelling methods',
'Operations Research',
'Operations Research',
'Operations Research',
'Operations Research',
'Operations Research',
'Operations Research',
'Operations Research',
'Optimisation',
'Optimisation',
'Optimisation',
'Optimisation',
'Optimisation',
'Optimisation',
'Optimisation',
'Simulation',
'Simulation',
'Simulation',
'Simulation',
'Simulation',
'Simulation',
'Simulation',
'Use Cloud Computing technologies',
'Use Cloud Computing technologies',
'Use Cloud Computing technologies',
'Use Cloud Computing technologies',
'Use Cloud Computing technologies',
'Use Cloud Computing technologies',
'Use Cloud Computing technologies',
'organisational Information systems',
'organisational Information systems',
'organisational Information systems',
'organisational Information systems',
'organisational Information systems',
'organisational Information systems',
'organisational Information systems',
'Design efficient algorithms for large amounts of data',
'Design efficient algorithms for large amounts of data',
'Design efficient algorithms for large amounts of data',
'Design efficient algorithms for large amounts of data',
'Design efficient algorithms for large amounts of data',
'Design efficient algorithms for large amounts of data',
'Design efficient algorithms for large amounts of data',
'Recommender or Ranking system',
'Recommender or Ranking system',
'Recommender or Ranking system',
'Recommender or Ranking system',
'Recommender or Ranking system',
'Recommender or Ranking system',
'Recommender or Ranking system',
'enterprise data management',
'enterprise data management',
'enterprise data management',
'enterprise data management',
'enterprise data management',
'enterprise data management',
'enterprise data management',
'implementation of the hybrid data management infrastructure',
'implementation of the hybrid data management infrastructure',
'implementation of the hybrid data management infrastructure',
'implementation of the hybrid data management infrastructure',
'implementation of the hybrid data management infrastructure ',
'implementation of the hybrid data management infrastructure',
'implementation of the hybrid data management infrastructure',
'Develop and implement data architecture',
'Develop and implement data architecture',
'Develop and implement data architecture',
'Develop and implement data architecture',
'Develop and implement data architecture',
'Develop and implement data architecture',
'Develop and implement data architecture',
'Consistently implement data curation and data quality controls',
'Consistently implement data curation and data quality controls',
'Consistently implement data curation and data quality controls',
'Consistently implement data curation and data quality controls',
'Consistently implement data curation and data quality controls',
'Consistently implement data curation and data quality controls',
'Consistently implement data curation and data quality controls',
'Implement data protection',
'Implement data protection',
'Implement data protection',
'Implement data protection',
'Implement data protection',
'Implement data protection',
'Implement data protection',
'Adhere to the principles of the Open Data',
'Adhere to the principles of the Open Data',
'Adhere to the principles of the Open Data',
'Adhere to the principles of the Open Data',
'Adhere to the principles of the Open Data',
'Adhere to the principles of the Open Data',
'Adhere to the principles of the Open Data',
'developing data driven applications',
'developing data driven applications',
'developing data driven applications',
'developing data driven applications',
'developing data driven applications',
'developing data driven applications',
'developing data driven applications',
'data collection process',
'data collection process',
'data collection process',
'data collection process',
'data collection process',
'data collection process',
'data collection process',
'Apply structured approach to use cases analysis',
'Apply structured approach to use cases analysis',
'Apply structured approach to use cases analysis',
'Apply structured approach to use cases analysis',
'Apply structured approach to use cases analysis',
'Apply structured approach to use cases analysis',
'Apply structured approach to use cases analysis',
'Develop and implement Research Data Management Plan',
'Develop and implement Research Data Management Plan',
'Develop and implement Research Data Management Plan',
'Develop and implement Research Data Management Plan',
'Develop and implement Research Data Management Plan',
'Develop and implement Research Data Management Plan',
'Develop and implement Research Data Management Plan',
'Consistently apply project management workflow',
'Consistently apply project management workflow',
'Consistently apply project management workflow',
'Consistently apply project management workflow',
'Consistently apply project management workflow ',
'Consistently apply project management workflow',
'Consistently apply project management workflow',
'Apply structured approach to use cases analysis in business and industry',
'Apply structured approach to use cases analysis in business and industry',
'Apply structured approach to use cases analysis in business and industry',
'Apply structured approach to use cases analysis in business and industry',
'Apply structured approach to use cases analysis in business and industry',
'Apply structured approach to use cases analysis in business and industry',
'Apply structured approach to use cases analysis in business and industry',
'Mechanism Design and/or Latent Dirichlet Allocation',
'Mechanism Design and/or Latent Dirichlet Allocation',
'Mechanism Design and/or Latent Dirichlet Allocation',
'Mechanism Design and/or Latent Dirichlet Allocation',
'Mechanism Design and/or Latent Dirichlet Allocation ',
'Mechanism Design and/or Latent Dirichlet Allocation',
'Mechanism Design and/or Latent Dirichlet Allocation']